filebeat:
  inputs:
    - type: log
      paths:
        - /logs/**/*.log.json
      json:
        keys_under_root: true # maps all properties under the path json to the root properties
        overwrite_keys: true # override the properties from the json path when they already exists
output.logstash:
  hosts: ["graylog:5044"]
logging.level: debug